In [1]:
n=list(map(str,input("enter").split()))
sum=0
for i in n:
x=int(i[1])
sum+=x
print(sum)


IndentationError: expected an indented block (<ipython-input-1-e4d6dfbcecc0>, line 4)

## data analysis
- any useful information is called as data
- types of data in devices
- .txt,.img,.ppt,.mp3,.excel,.doc etc
 types of data in relatime
1. quantitative data
-represent the size/volume of data
-discrete and continuos
- discrete:data is constant/fixed
ex:numbers in dice,color,nationality etc
- continuos data means the value/data is continuos
ex:time,height,weight
2. qualitative data
-data is analyised and categorized
- ex:data submission in feedback form
- data is statistics
  - nominal,ordinaal,intreval and ratio
  -nominal means data is categorised on the dasis of names
  - ex:color,nationality,gender
  -ordinal means data is actegorized upon the order value
  - ex: feedback form
  -interval means a range of interval values
  - ex:time interval in clock
  -ratio means data is meaningfully,added,subtracted,multiplied(ratios)
 


In [7]:
## numpy
import numpy as np
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

In [ ]:
np.__version__

In [2]:
# numpy means numerical python
# which is used to deal with arrays and scientific
# computation
# array(): methode to create
#numpy.array([iterable])

In [8]:
np.array([1,2,3,4,5,6,7,8])


array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
np.array([1,2,3,4,5],dtype="float")

array([1., 2., 3., 4., 5.])

In [10]:
np.array([1,2,3,4,5],dtype="int")

array([1, 2, 3, 4, 5])

In [ ]:
np.array([1,2,3,4,5],dtype="str")

In [ ]:
np.array([1,2,3,4,5],dtype="str")

In [ ]:
a=np.array(range(1,10))
a

In [ ]:
a=np.array(range(1,100))
a

In [ ]:
# print array starts from 1 to 50 skip by 2
b=np.array(range(1,51,3))
b

In [ ]:
##print array starts from 100 to 50 skip by 2
a=np.array(range(100,50,-1))
a

In [ ]:
print an array starts from 50 to 1 skip by 2 elemnts
a=np.array(range(100,50,-3))
a

In [ ]:
b=np.array([[1,2,3],[4,5,6]])
b

In [ ]:
b.ndim

In [ ]:
b.size

In [ ]:
b.size # no.of elements in array

In [ ]:
b.shape

In [ ]:
b.dtype

In [ ]:
b=np.array([[[1,2,3],[4,5,6]],[[4,5,6],[7,8,9]]])
b

In [ ]:
b.shape

In [ ]:
b.size 

In [ ]:
b.ndim

In [ ]:
b.dtype

In [ ]:
b.size # no.of elements in array

In [ ]:
##retriving elements using index positions

In [ ]:
# 1-d array
a=np.array([1,2,3,4,5])
a[2]


In [ ]:
# 2-d array
b=np.array([[1,2,3],[4,5,6]])
b[0,2]

In [16]:
## n-d array
a=np.array([1,2,3,4],ndmin=3)
a

array([[[1, 2, 3, 4]]])

In [14]:
## n-d array
a=np.array([1,2,3,4],ndmin=8)
a

array([[[[[[[[1, 2, 3, 4]]]]]]]])

In [ ]:
## creating another arrays


In [13]:
i=np.eye(8)
i

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
## creating null matrix
a=np.zeros(4,)
a

In [ ]:
a=np.zeros((4,4))
a

In [ ]:
##creating unit matrix
b=np.ones(4,dtype="int")
b

In [ ]:
o=np.ones((4,3))
o

In [ ]:
a=np.full(5,"hello")
a

In [ ]:
b=np.full((5,5),"hello")
b

In [ ]:
b.fill(4)
b

In [ ]:
## arange method
import numpy as np
a=np.arange(20)
a

In [ ]:
## print array using arange method
a=np.arange(100,0,-1)
a

In [ ]:
#constructing 2d-array from id-array
a=np.arange(10)
a

In [ ]:

b=np.arange(100,20,-4)
b

In [ ]:
b.reshape(4,5)

In [ ]:
## random
a=np.random.randint(15)
a

In [ ]:
a=np.random.randint(10,90)
a

In [ ]:
lw,uw=int(input()),int(input())
b=np.random.randint(lw,uw,10)
b.reshape(2,5)

In [18]:
import numpy as np
c=np.random.randn(4,5)
c

array([[ 1.12555692, -1.38317269, -1.87213413,  0.88831615,  1.96392288],
       [-1.23034713,  1.05682675,  0.12407917, -0.95361283, -0.35364462],
       [ 0.69963476,  0.22208056, -0.83975105, -2.02396837, -0.24616214],
       [-2.61595326,  0.92898141,  0.62413191,  1.23738627, -0.00893148]])

In [17]:
##linespace()
import numpy as np
a=np.linspace(31,31)
a

array([31., 31., 31., 31., 31., 31., 31., 31., 31., 31., 31., 31., 31.,
       31., 31., 31., 31., 31., 31., 31., 31., 31., 31., 31., 31., 31.,
       31., 31., 31., 31., 31., 31., 31., 31., 31., 31., 31., 31., 31.,
       31., 31., 31., 31., 31., 31., 31., 31., 31., 31., 31.])

In [12]:
import numpy as np
a=np.arange(10).reshape(2,5)
print(a)
print(a.transpose())



[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [11]:
a=np.arange(20).reshape(4,5)
print(a)
print(a[0,2:5])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[2 3 4]


In [21]:
##arithematic operations on array
a=np.array([[1,2,3]])
b=np.array([[4,5,6]])
c=a+b
c


array([[5, 7, 9]])

In [22]:
c=a-b
c

array([[-3, -3, -3]])

In [23]:
c=a*b
c

array([[ 4, 10, 18]])

In [24]:
c=a/b
c

array([[0.25, 0.4 , 0.5 ]])

In [26]:
#scientific calculations
np.log(1)

0.0

In [27]:
a=np.log([1,2,3])
a


array([0.        , 0.69314718, 1.09861229])

In [28]:
a=np.sin([1,2,3,4])
a

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [29]:
# statistics
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [30]:
print(np.amin(a))


1


In [31]:
print(np.amax(a))


6


In [33]:
a=np.array([4,5,6])
print(np.mean(a))
print(np.median(a))



5.0
5.0


In [34]:
# standard deviation
## square root of average of square deviations of mean
print(np.std(a))

0.816496580927726


In [35]:
## varaince
## average of squares of  standard deviation
print(np.var(a))

0.6666666666666666


In [38]:
print(np.sum(a))
print(np.prod(a))
print(np.cumsum(a))
print(np.cumprod(a))
print(np.all(a))
print(np.any(a))


     


15
120
[ 4  9 15]
[  4  20 120]
True
True


In [41]:
#filtering
a=np.array([51,52,53,54,55])
f=a>52
n=a[f]
print(f)
print(n)



[False False  True  True  True]
[53 54 55]


In [44]:
b=np.array([2,4,6,10,7,11,13])
f=b%2==0
n=b[f]
print(f)
print(n)

[ True  True  True  True False False False]
[ 2  4  6 10]


In [45]:
# saving the data
from numpy import array
from numpy import savetxt
data=np.array([[1,2,3,4],[3,4,5,6]])
savetxt('data.csv',data,delimiter=",")


In [48]:
## displaying the data from .csv file
from numpy import loadtxt
data=loadtxt('data.csv',delimiter=",")
data

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.]])